# Config file for model training
name = 'stockholm_model'
label = 'trade_signal'
features = [
    'RSI_14', 'SUPERT_7_3.0', 'SUPERTd_7_3.0', 'SUPERTl_7_3.0',
    'SUPERTs_7_3.0', 'BBL_5_2.0', 'BBM_5_2.0', 'BBU_5_2.0',
    'BBB_5_2.0', 'BBP_5_2.0', 'STOCHRSIk_14_14_3_3',
    'STOCHRSId_14_14_3_3', 'open', 'high', 'low', 'close', 'volume',
    'pe'
]
pos_weight = 25

[training]
start_date = '2012-01-01'
end_date = '2022-12-31'

[evaluation]
start_date = '2024-01-01'
end_date = '2024-12-31'

[[models]]
type = 'XGBClassifier'

[models.hyperparameters]
learning_rate = 0.1
n_estimators = 1000
max_depth = 5
min_child_weight = 2

[[models]]
type = 'LGBMClassifier'

[models.hyperparameters]
n_estimators = 1000
