[theme]
base = "light"
primaryColor = '#064E3B'
backgroundColor = "#EFF1EF"
# backgroundColor = '#F5F8F6'
secondaryBackgroundColor = "#d7e0dd"
dataframeHeaderBackgroundColor = '#d7e0dd'

[theme.sidebar]
backgroundColor = "#14532D"

[server]
enableStaticServing = true
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
